// ============================================================================
// Scheduler types — shared between engine, store, API, and UI
// ============================================================================

export interface PromptTaskConfig {
  cwd: string;
  message: string;
  model?: { provider: string; modelId: string };
  toolNames?: string[];
}

/** Single execution record */
export interface TaskLog {
  id: string;
  timestamp: string;
  result: "success" | "error";
  error?: string;
  /** First ~500 chars of the agent's final output */
  output?: string;
  durationMs: number;
  /** Session generated by this scheduled execution, if available */
  sessionId?: string;
  sessionFile?: string;
}

export interface ScheduledTask {
  id: string;
  name: string;
  type: "prompt";
  cron: string;
  enabled: boolean;
  config: PromptTaskConfig;
  createdAt: string;
  lastRunAt?: string;
  lastResult?: "success" | "error";
  lastError?: string;
  /** How many times this task has been executed */
  runCount: number;
  /** Execution logs, most recent first. Capped at 50 entries. */
  logs: TaskLog[];
}

export interface TaskStore {
  tasks: ScheduledTask[];
}

// For the API response — excludes internal fields if needed
export type ScheduledTaskSummary = Pick<
  ScheduledTask,
  "id" | "name" | "type" | "cron" | "enabled" | "createdAt" | "lastRunAt" | "lastResult" | "runCount"
>;
